[package]
name = "osqp"
version = "0.0.1-pre.1"
authors = ["Edward Barnard <eabarnard@gmail.com>"]
license = "MIT/Apache-2.0"

[workspace]

[dependencies]
osqp-sys = { version = "0.2.1-pre.1", path = "osqp-sys" }
static_assertions = "0.2.3"
