[package]
name = "osqp"
version = "0.0.1-pre.2"
description = "The OSQP (Operator Splitting Quadratic Program) solver."
authors = ["Edward Barnard <eabarnard@gmail.com>"]
license = "Apache-2.0"
homepage = "https://osqp.readthedocs.io/"
repository = "https://github.com/ebarnard/osqp.rs/"
documentation = "https://docs.rs/osqp/0.0.1-pre.2/osqp/"
keywords = ["optimisation", "optimization", "solver", "quadratic", "linear"]

[workspace]

[dependencies]
osqp-sys = { version = "0.2.1-pre.2", path = "osqp-sys" }
static_assertions = "0.2.3"
