[package]
name = "osqp"
version = "0.1.0"
authors = ["Edward Barnard <eabarnard@gmail.com>"]
license = "MIT/Apache-2.0"

[workspace]

[dependencies]
osqp-sys = { version = "0.1.3", path = "osqp-sys" }
static_assertions = "0.2.3"