[package]
name = "osqp-sys"
version = "0.2.1-pre.2"
description = "FFI bindings to the OSQP (Operator Splitting Quadratic Program) solver."
authors = ["Edward Barnard <eabarnard@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/ebarnard/osqp.rs/"
documentation = "https://docs.rs/osqp-sys/0.2.1-pre.2/osqp-sys/"
categories = ["external-ffi-bindings"]
links = "osqp"

[build-dependencies]
cmake = "0.1.28"
