[package]
name = "osqp-sys"
version = "0.3.1"
description = "FFI bindings to the OSQP (Operator Splitting Quadratic Program) solver."
authors = ["Edward Barnard <eabarnard@gmail.com>"]
license = "Apache-2.0"
homepage = "https://osqp.readthedocs.io/"
repository = "https://github.com/oxfordcontrol/osqp.rs/"
documentation = "https://docs.rs/osqp-sys/0.3.1/"
categories = ["external-ffi-bindings"]
links = "osqp"

[build-dependencies]
cmake = "0.1.28"
